development:
  clients:
    default:
      database: sinatra_blog
      hosts:
        - 127.0.0.1:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ<em>URL'] %>
      options:
        skip_version_check: true
        safe: true        